name: Build StrongApp APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-setuptools \
            git zip unzip openjdk-17-jdk \
            libffi-dev libssl-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Accept Android SDK licenses
        run: |
          mkdir -p ~/.android
          echo '### User Sources for Android SDK Manager' > ~/.android/repositories.cfg
          yes | buildozer android accept_license || true

      - name: Initialize Buildozer
        run: |
          buildozer init || true

      - name: Build APK
        run: |
          buildozer android debug || exit 1

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: StrongApp-APK
          path: bin/*.apk
